define([], function() {
  return {
    ThemeValuePostLabel: "Vous pouvez utiliser <pre style='display:inline;font-weight:700;'>ColorValue(Param('themevaluename'))</pre> dans vos Power Apps pour récupérer toutes les valeurs de couleur de thème que vous avez sélectionnées.",
    ThemeValueFieldLabel: "Propriétés de la variante du thème",
    ThemeValuePreLabel: "Sélectionnez les couleurs du thème que vous souhaitez transmettre à votre application. Vous pouvez l'utiliser pour rendre votre application sensible aux thèmes.",
    ThemeGroupName: "Thème",
    DynamicsPropNameDescriptionLabel: "Quel nom voulez-vous utiliser lorsque vous récupérez ce paramètre dans Power Apps ? Par exemple : 'id'.",
    DynamicPropsNameFieldLabel: "Nom du paramètre",
    DynamicPropFieldLabel: "Source de propriété dynamique",
    SelectDynamicSource: "Sélectionnez une source de propriété dynamique",
    UseDynamicPropsFieldLabel: "Passer une propriété dynamique en tant que paramètre ?",
    DynamicsPropsGroupDescription2: "Notez que nous transmettons toujours la langue de la page. Utiliser<pre style='display:inline;font-weight:700;'>Param('locale')</pre> pour récupérer la valeur dans Power Apps.",
    DynamicsPropsGroupDescription1: "Vous pouvez transmettre des propriétés dynamiques de l'environnement de la page ou d'autres parties Web de la page en tant que paramètres à Power Apps. Dans Power Apps, vous pouvez utiliser <pre style='display:inline;font-weight:700;'>Param('{0}')</pre> pour récupérer la valeur.",
    DynamicPropertiesGroupLabel: "Propriétés dynamiques",
    WidthFieldLabel: "Largeur",
    AspectRatioCustomOption: "Custom",
    AspectRatioFieldLabel: "Rapport hauteur/largeur",
    HeightFieldLabel: "Hauteur",
    LayoutAspectRatioOption: "Redimensionner proportionnellement",
    LayoutFixedHeightOption: "Hauteur fixe",
    LayoutFieldLabel: "Comportement de redimensionnement",
    BorderFieldLabel: "Afficher la bordure",
    AppearanceGroupName: "Apparence",
    PlaceholderButtonLabel: "Ajouter une application",
    PlaceholderDescription: "Incluez une application professionnelle personnalisée sur votre page.",
    PlaceholderIconText: "Enhanced Microsoft Power Apps",
    PropertyPaneDescription: "Ajoutez une application professionnelle personnalisée en collant son lien web ou son identifiant ci-dessous.",
    BasicGroupName: "Configuration de base",
    AppWebLinkFieldLabel: "Lien web ou ID de l'application",
    StaticPropertiesGroupLabel: "Propriétés statiques",
    StaticPropertiesGroupDescription: "Vous pouvez transmettre des propriétés statiques à PowerApps.<br/>Dans Power Apps, vous pouvez utiliser <pre style='display:inline;font-weight:700;'>Param('{0}')</pre> pour récupérer la valeur.",
    StaticPropertyNameFieldLabel: "Nom de la propriété",
    StaticPropertyValueLabel: "Valeur de la propriété",
    UseStaticPropsFieldLabel: "Passer une propriété statique en tant que paramètre ?"
  }
});
